{
    "camera": "Generated by Roboflow",
    "classes": {
        "nobel gel 40": 10,
        "zerodol p": 10,
        "10 day": 10,
        "pancom lsr": 10
    },
    "datasets": [
        "d7JTg8EleEL0JXCpb1yq"
    ],
    "destination": "8e7b5f9f61b59a2351fe476c2e841ec3",
    "height": 640,
    "id": "4EgMGERDEvQhU4dn2Q85",
    "label": [],
    "labels": [],
    "name": "d2.jpeg",
    "numSteps": 2,
    "owner": "PJUqMkuBGFaQ7kt1SQJhTNSSuRD2",
    "predictionBoxes": [],
    "preprocessing": [
        "auto-orient",
        "resize:[\"Stretch to\",640,640]"
    ],
    "preprocessingParsed": [
        {
            "name": "Auto-Orient",
            "value": "Applied"
        },
        {
            "name": "Resize",
            "value": "Stretch to 640x640"
        }
    ],
    "source": "4EgMGERDEvQhU4dn2Q85",
    "split": "test",
    "split.d7JTg8EleEL0JXCpb1yq.2": "test",
    "status": "generated",
    "transforms": "[\n    \"auto-orient\",\n    \"resize:[\\\"Stretch to\\\",640,640]\"\n]",
    "updated": {
        "_seconds": 1676440569,
        "_nanoseconds": 798000000
    },
    "updatedDate": "Feb 15, 2023",
    "updatedTime": "11:26AM",
    "updatedTimezone": "+05:30",
    "versions": [
        "d7JTg8EleEL0JXCpb1yq/2"
    ],
    "width": 640
}

{
    "boxes": [
        {
            "label": "zerodol p",
            "x": 450.5,
            "y": 386,
            "width": 197.5,
            "height": 27
        },
        {
            "label": "pancom lsr",
            "x": 451,
            "y": 421,
            "width": 196.5,
            "height": 22.5
        },
        {
            "label": "nobel gel 40",
            "x": 424.5,
            "y": 455.5,
            "width": 161,
            "height": 26
        },
        {
            "label": "10 day",
            "x": 603,
            "y": 395.5,
            "width": 73.5,
            "height": 23.5
        }
    ],
    "height": 640,
    "key": "d2.jpeg",
    "width": 640
}